{
 "title": "Lukso",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Validator Balance (LYX)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance{job=\"validator\"})) or\n((sum(validator_monitor_balance_gwei > 16E9))/1E9)",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of LYX in USD.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd ", "legendFormat": "lyxusd" },
    {
     "expr": "(sum(validator_balance{job=\"validator\"})) or\n((sum(validator_monitor_balance_gwei > 16E9))/1E9)",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "LYX Price (USD)",
   "type": "stat",
   "description": "Price of Lyx in USD.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd", "legendFormat": "lyxusd" }
   ]
  },
  {
   "title": "Total Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vc_beacon_attester_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Enabled Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vc_validators_enabled_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei > 16E9))/1E9",
     "legendFormat": "Total balance"
    }
   ]
  },
  {
   "title": "Enabled Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Validators" }
   ],
   "targets": [
    { "expr": "vc_validators_enabled_count" }
   ]
  },
  {
   "title": "Local Attesters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    { "expr": "vc_beacon_attester_count" }
   ]
  },
  {
   "title": "Local Block Proposers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    { "expr": "vc_beacon_block_proposer_count" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "bargauge",
   "description": "Peers via client implementations",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "libp2p_peers_per_client", "legendFormat": "{{Client}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "sum(sync_peers_per_status{job=\"beacon node\", sync_status=~\"Synced|Advanced\"}) OR # Lighthouse\nlodestar_peers_sync_count{job=\"beacon node\"} OR # Lodestar\nnbc_peers{job=\"beacon node\"} OR # Nimbus\np2p_peer_count{job=\"beacon node\", state=\"Connected\"} OR # Prysm\nbeacon_peer_count{job=\"beacon node\"} # Teku",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(log_entries_total{job=\"validator\", level=\"error\"}[$__range]))*3600) or\n(sum(rate(error_total{job=\"validator\"}[$__range]))*60)",
     "legendFormat": "errors"
    },
    {
     "expr": "(sum(rate(log_entries_total{job=\"validator\", level=\"warning\"}[$__range]))*3600) or\nsum(rate(warn_total{job=\"validator\"}[$__range]))*60",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(log_entries_total{job=\"beacon node\", level=\"error\"}[$__range]))*3600) or\n(sum(rate(error_total{job=\"beacon node\"}[$__range]))*60)",
     "legendFormat": "errors"
    },
    {
     "expr": "(sum(rate(log_entries_total{job=\"beacon node\", level=\"warning\"}[$__range]))*3600) or\n(sum(rate(warn_total{job=\"beacon node\"}[$__range]))*60)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (validator) (validator_monitor_unaggregated_attestation_total)"
    },
    {
     "expr": "max by (validator) (validator_monitor_aggregated_attestation_total)"
    },
    {
     "expr": "max by (validator) (validator_monitor_beacon_block_total)"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(validator) (validator_monitor_balance_gwei/1E9)"
    },
    {
     "expr": "max by(validator) (validator_monitor_active)",
     "legendFormat": "Active"
    },
    {
     "expr": "max by(validator) (validator_monitor_slashed*1000)",
     "legendFormat": "Slashed"
    },
    {
     "expr": "max by(validator) (validator_monitor_exited*10)",
     "legendFormat": "Exited"
    },
    {
     "expr": "max by(validator) (validator_monitor_withdrawable*100)",
     "legendFormat": "Withdrawable"
    },
    {
     "expr": "validator_monitor_validator_in_current_sync_committee{}",
     "legendFormat": "Sync Committee"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"beacon node\"} or\nbeacon_head_state_active_validators_total{job=\"beacon node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"beacon node\"} or\nbeacon_head_state_slashed_validators_total{job=\"beacon node\"}",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"beacon node\"} or\nbeacon_head_state_withdrawn_validators_total{job=\"beacon node\"}",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"beacon node\"} or (\n    (eth1_deposit_cache_len - beacon_processed_deposits_total) + beacon_head_state_total_validators_total - beacon_current_active_validators\n)",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"beacon node\"} or\nbeacon_head_state_withdrawn_validators_total{job=\"beacon node\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",job=\"beacon node\"} or\nbeacon_head_state_slashed_validators_total{job=\"beacon node\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{job=\"beacon node\", state=\"Active\"} or\nbeacon_head_state_active_validators_total{job=\"beacon node\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"beacon node\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"beacon node\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"}) or\n(beacon_participation_prev_epoch_target_attesting_gwei_total{job=\"beacon node\"} / beacon_participation_prev_epoch_active_gwei_total{job=\"beacon node\"})"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"beacon node\"}/32) - beacon_finalized_epoch{job=\"beacon node\"} - 2)/100))),0) or\nclamp_min((1-(4*((floor(slotclock_present_slot{job=\"beacon node\"}/32) - beacon_finalized_epoch{job=\"beacon node\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"}) or\n(beacon_participation_prev_epoch_target_attesting_gwei_total{job=\"beacon node\"} / beacon_participation_prev_epoch_active_gwei_total{job=\"beacon node\"})",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Validator Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(eth1_deposit_cache_len - beacon_processed_deposits_total) or\n(beacondb_pending_deposits - beacon_processed_deposits_total + 1)",
     "legendFormat": "deposited"
    },
    {
     "expr": "beacon_processed_deposits_total or\n(beacon_processed_deposits_total - 1)",
     "legendFormat": "processed"
    },
    {
     "expr": "beacon_head_state_total_validators_total-beacon_current_active_validators",
     "legendFormat": "activating"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"beacon node\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"beacon node\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"beacon node\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Validator Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((beacon_head_state_total_validators_total-beacon_current_active_validators)/4)*6.4)",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(validators_total_balance{state=\"Active\",job=\"beacon node\"} / validator_count{state=\"Active\",job=\"beacon node\"} / 1000000000) or\n(beacon_head_state_validator_balances_total{job=\"beacon node\"} / beacon_head_state_total_validators_total{job=\"beacon node\"} / 1000000000)",
     "legendFormat": "lyx"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"beacon node\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval]))) or vector(0)))/count(irate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"beacon node\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval]))) or vector(0))) * 100 / (count (node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "(system_cpu_procload{job=\"geth\"} / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))) OR # Geth\nirate(process_cpu_seconds_total{job=\"eth1\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) # Besu, Nethermind",
     "legendFormat": "EC (Stacked)"
    },
    {
     "expr": "100 / (count (node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}))",
     "legendFormat": "Single Core Cap"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(process_resident_memory_bytes{job=\"beacon node\"}) + (sum(process_resident_memory_bytes{job=\"validator\"}) or vector(0)))/sum(node_memory_MemTotal_bytes{job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "timeseries",
   "description": "Memory usage on the server",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - node_memory_Buffers_bytes{job=\"node_exporter\"} - node_memory_Cached_bytes{job=\"node_exporter\"} - node_memory_SwapCached_bytes{job=\"node_exporter\"} - node_memory_Slab_bytes{job=\"node_exporter\"} - node_memory_PageTables_bytes{job=\"node_exporter\"} - node_memory_VmallocUsed_bytes{job=\"node_exporter\"} ) or ( node_memory_MemTotal{job=\"node_exporter\"} - node_memory_MemFree{job=\"node_exporter\"} - node_memory_Buffers{job=\"node_exporter\"} - node_memory_Cached{job=\"node_exporter\"} - node_memory_SwapCached{job=\"node_exporter\"} - node_memory_Slab{job=\"node_exporter\"} - node_memory_PageTables{job=\"node_exporter\"} - node_memory_VmallocUsed{job=\"node_exporter\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node_exporter\"} or node_memory_Buffers{job=\"node_exporter\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter\"} or node_memory_Cached{job=\"node_exporter\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"} or node_memory_MemFree{job=\"node_exporter\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node_exporter\"} or node_memory_Slab{job=\"node_exporter\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "timeseries",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"beacon node\"}",
     "legendFormat": "beacon memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"validator\"}",
     "legendFormat": "validator memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg (irate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1.0-node_memory_MemAvailable_bytes{job=\"node_exporter\"}/node_memory_MemTotal_bytes{job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node_exporter\"})-sum(node_filesystem_avail_bytes{job=\"node_exporter\"}))/sum(node_filesystem_size_bytes{job=\"node_exporter\"})"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node_exporter\"})-sum(node_filesystem_avail_bytes{job=\"node_exporter\"})",
     "legendFormat": "used space"
    }
   ]
  },
  {
   "title": "Block Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "State Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Times (24s moving avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum[30s])\n/\nrate(beacon_block_processing_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"ping_google\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"ping_cloudflare\"}",
     "legendFormat": "cloudflare"
    }
   ]
  },
  {
   "title": "Find & Update Head Routine (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum[1m])\n/\nrate(beacon_fork_choice_seconds_count[1m])"
    }
   ]
  }
 ]
}